version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/tmp:/var/lib/postgresql/data
      - ./db/sql/initdb:/docker-entrypoint-initdb.d
      - ./db/sql:/sql/
  back:
    image: openjdk:17
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./back:/srv:cached
      - ./back/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh","/entrypoint.sh", "${DEV_ENV}"]
    working_dir: /srv
    depends_on:
      - db
  front:
    image: node:lts-bullseye
    ports:
      - '3000:3000'
    working_dir: /front
    volumes:
      - ./front:/front:cached
    command: sh -c 'yarn start'

volumes:
  postgres:
